import streamlit as st
import joblib
import pandas as pd

st.set_page_config(
    page_title="Bank Loan Risk Analysis",
    page_icon="🏦",
    layout="wide"
)

# Professional blue dashboard style
st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #eef5ff, #ffffff);
}
[data-testid="stHeader"] {
    background: rgba(255,255,255,0);
}
.main .block-container {
    padding-top: 2rem;
    max-width: 1100px;
}
.hero {
    background: linear-gradient(120deg, #123a72, #1976d2);
    padding: 30px;
    border-radius: 18px;
    color: white;
    margin-bottom: 24px;
}
.hero h1 {
    color: white;
    margin-bottom: 8px;
}
.hero p {
    color: #e6f1ff;
    font-size: 17px;
}
div.stButton > button {
    background: #1769aa;
    color: white;
    border-radius: 10px;
    border: none;
    padding: 12px 22px;
    font-weight: bold;
    width: 100%;
}
div.stButton > button:hover {
    background: #0d47a1;
    color: white;
}
div[data-testid="stMetric"] {
    background: white;
    padding: 18px;
    border-radius: 14px;
    border: 1px solid #d8e6f7;
    box-shadow: 0 3px 12px rgba(20, 70, 130, 0.07);
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
    <h1>🏦 Bank Loan Risk Analysis</h1>
    <p>Machine Learning Powered Loan Status Prediction Dashboard</p>
</div>
""", unsafe_allow_html=True)

st.warning(
    "Educational demo only. Predictions are not real bank loan decisions."
)

@st.cache_resource
def load_model():
    return joblib.load("loan_model.pkl")

try:
    model = load_model()
except Exception as e:
    st.error("Model could not be loaded. Please check loan_model.pkl.")
    st.stop()

st.subheader("📋 Customer Information")
st.write("Enter the details below to predict the demo loan status.")

st.subheader("📊 Model Performance")

metric_col1, metric_col2 = st.columns(2)

with metric_col1:
    st.metric("Model Accuracy", "100.00%")

with metric_col2:
    st.metric("Test Records", "40")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input(
        "👤 Customer Age",
        min_value=18,
        max_value=100,
        value=30
    )
    income = st.number_input(
        "💰 Annual Income (₹)",
        min_value=0,
        value=50000,
        step=5000
    )

with col2:
    loan_amount = st.number_input(
        "🏠 Loan Amount (₹)",
        min_value=0,
        value=20000,
        step=5000
    )
    credit_score = st.number_input(
        "📊 Credit Score",
        min_value=300,
        max_value=900,
        value=750
    )

st.divider()

if st.button("🔍 Predict Loan Status"):
    input_data = pd.DataFrame(
        [[age, income, loan_amount, credit_score]],
        columns=["Age", "Income", "LoanAmount", "CreditScore"]
    )

    prediction = model.predict(input_data)[0]

    st.subheader("📌 Prediction Result")

    result_col1, result_col2 = st.columns(2)

    with result_col1:
        st.metric("Annual Income", f"₹{income:,.0f}")

    with result_col2:
        st.metric("Credit Score", credit_score)

    if prediction == 1:
        st.success("✅ Demo Prediction: APPROVED")
        st.balloons()
    else:
        st.error("❌ Demo Prediction: REJECTED")

    st.caption(
        "This result is generated by the project's trained Decision Tree model."
    )

st.divider()
st.caption("College Project | Python • Pandas • Scikit-learn • Streamlit")

st.divider()

st.header("📊 Model Evaluation — Confusion Matrix")

try:
    confusion_df = pd.read_csv("confusion_matrix.csv")

    st.write("Confusion matrix for the trained model:")
    st.dataframe(confusion_df, use_container_width=True)

    st.download_button(
        label="⬇️ Download Confusion Matrix CSV",
        data=confusion_df.to_csv(index=False),
        file_name="confusion_matrix.csv",
        mime="text/csv"
    )

except FileNotFoundError:
    st.warning(
        "confusion_matrix.csv was not found. "
        "Please check that it is uploaded to the GitHub repository."
    )
