import streamlit as st
import joblib
import pandas as pd

st.set_page_config(
    page_title="Bank Loan Risk Analysis",
    page_icon="🏦",
    layout="centered"
)

st.title("🏦 Bank Loan Risk Analysis")
st.write("Enter customer details to view a Machine Learning prediction.")

st.warning(
    "Educational demo only. This is not a real bank loan decision system."
)

@st.cache_resource
def load_model():
    return joblib.load("loan_model.pkl")

model = load_model()

age = st.number_input("Customer Age", min_value=18, max_value=100, value=30)
income = st.number_input("Annual Income (₹)", min_value=0, value=50000, step=5000)
loan_amount = st.number_input("Loan Amount (₹)", min_value=0, value=20000, step=5000)
credit_score = st.number_input("Credit Score", min_value=300, max_value=900, value=750)

if st.button("Predict Loan Status"):
    input_data = pd.DataFrame(
        [[age, income, loan_amount, credit_score]],
        columns=["Age", "Income", "LoanAmount", "CreditScore"]
    )

    prediction = model.predict(input_data)[0]

    if prediction == 1:
        st.success("Demo Prediction: Approved ✅")
    else:
        st.error("Demo Prediction: Rejected ❌")

st.caption("Prediction is generated by the project's trained Decision Tree model.")
